version: '3'
services:
  node-express:
    build: .
    image: node-express
    container_name: node-express
    environment:
      NODE_ENV: development
    working_dir: /app
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
